# Generated by Django 2.2 on 2019-07-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190703_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
