# Generated by Django 2.2 on 2019-06-03 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_types', '0001_initial'),
        ('counties', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='images/event/%Y/%m/%d/')),
                ('cover_image', models.ImageField(blank=True, upload_to='images/event/%Y/%m/%d/')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='categories.Category')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counties.County')),
                ('event_type', models.ManyToManyField(to='event_types.EventType')),
            ],
        ),
    ]
