# Generated by Django 2.2 on 2019-07-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('events', '0008_event_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genres.Genre'),
        ),
    ]
