# Generated by Django 2.2.3 on 2020-06-01 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drink_categories', '0001_initial'),
        ('clubs', '0008_auto_20191101_0120'),
        ('alcohol', '0001_initial'),
        ('drink_glass_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cocktail_image', models.ImageField(upload_to='images/cocktail/%Y/%m/%d/')),
                ('block_quote', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('cocktail_recipe_author', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('alcohol', models.ManyToManyField(blank=True, to='alcohol.Alcohol')),
                ('categories', models.ManyToManyField(blank=True, to='drink_categories.DrinkCategory')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
                ('glass_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drink_glass_types.GlassType')),
            ],
        ),
    ]
