# Generated by Django 2.2.3 on 2020-06-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0001_initial'),
        ('cocktails', '0002_cocktail_video_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='alcohol',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='alcohol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alcohol.Alcohol'),
        ),
    ]
