# Generated by Django 2.2.3 on 2020-06-01 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alcohol', '0001_initial'),
        ('blog_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('blog_image', models.ImageField(upload_to='images/blog/%Y/%m/%d/')),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('first_paragraph', models.TextField(blank=True, null=True)),
                ('middle_paragragh', models.TextField(blank=True, null=True)),
                ('final_paragragh', models.TextField(blank=True, null=True)),
                ('blog_author', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(blank=True, max_length=200)),
                ('reading_time', models.CharField(blank=True, max_length=2, null=True)),
                ('blog_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcohol.Alcohol')),
                ('categories', models.ManyToManyField(to='blog_categories.BlogCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.Blog')),
            ],
        ),
    ]
