# Generated by Django 2.2.3 on 2020-06-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drink_categories', '0001_initial'),
        ('blogs', '0001_initial'),
        ('cocktails', '0001_initial'),
        ('drink_glass_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cocktail',
            field=models.ManyToManyField(to='cocktails.Cocktail'),
        ),
        migrations.AddField(
            model_name='blog',
            name='drink_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink_categories.DrinkCategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='glass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink_glass_types.GlassType'),
        ),
    ]
