# Generated by Django 2.2.3 on 2020-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200601_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(blank=True, max_length=66),
        ),
    ]
