# Generated by Django 2.2.3 on 2020-06-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200604_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='alcohol',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='alcohol.Alcohol'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cocktail',
            field=models.ManyToManyField(blank=True, to='cocktails.Cocktail'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='drink_categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drink_categories.DrinkCategory'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='glass_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drink_glass_types.GlassType'),
        ),
    ]
