# Generated by Django 2.2.3 on 2020-06-04 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200604_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='alcohol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alcohol.Alcohol'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='county',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='drink_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drink_categories.DrinkCategory'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='first_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='glass_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drink_glass_types.GlassType'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(max_length=66),
        ),
    ]
