# Generated by Django 2.2 on 2019-07-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='county',
        ),
    ]
