# Generated by Django 2.2 on 2019-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
