# Generated by Django 2.2 on 2019-07-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0003_auto_20190627_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'counties'},
        ),
    ]
