# Generated by Django 2.2 on 2019-07-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
    ]
