# Generated by Django 2.2 on 2019-07-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0004_auto_20190712_1358'),
        ('clubs', '0002_auto_20190713_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counties.County'),
        ),
        migrations.AddField(
            model_name='club',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
