# Generated by Django 2.2.3 on 2019-10-07 03:24

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20191007_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='reservation',
        ),
        migrations.AddField(
            model_name='club',
            name='reservation_number',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
