# Generated by Django 2.2.3 on 2019-10-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20191007_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='reservation_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
