# Generated by Django 2.2.3 on 2019-10-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_description_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
